export enum LocalStorageKeys {
  MISSING_EMAIL_TOAST_LAST_SHOWN_DATE = 'MISSING_EMAIL_TOAST_LAST_SHOWN_DATE',
  RECENT_DOMAINS = 'RECENT_DOMAINS',
  ANONYMOUS_CART = 'ANONYMOUS_CART',
  ANONYMOUS_WISHLIST = 'ANONYMOUS_WISHLIST',
  FEEDBACK_PROMPT_STATE = 'FEEDBACK_PROMPT_STATE',
  FEEDBACK_USAGE_SECONDS = 'FEEDBACK_USAGE_SECONDS',
  FEEDBACK_SUBMISSIONS = 'FEEDBACK_SUBMISSIONS',
}
