import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import { Preloader } from '@/components/preloader';
import { AppSidebar } from '@/components/sidebars';
import { SidebarInset, SidebarProvider } from '@/components/ui/shadcn/sidebar';
import { Toaster } from '@/components/ui/shadcn/sonner';
import { Contexts } from '@/contexts';
import { config } from '@/lib/env';
import { cn } from '@/lib/utils';
import { Providers } from '@/providers';
import { GoogleAnalytics } from '@next/third-parties/google';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import type { ReactNode } from 'react';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          'antialiased min-h-screen w-full overflow-x-hidden overflow-y-auto',
        )}
      >
        <Preloader />
        <GoogleAnalytics gaId={config.GA_MEASUREMENT_ID} />
        <Providers>
          <Contexts>
            <Toaster />

            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <Header className="sticky z-10 backdrop-blur-xl top-0 left-0" />
                {children}
                <Footer className="hidden" />
              </SidebarInset>
            </SidebarProvider>
          </Contexts>
        </Providers>
      </body>
    </html>
  );
}
