import { User, Briefcase, Music, Heart, Star, Trophy } from 'lucide-react';
import { generateCVConfig } from '../lib/generate-config';

const { landingConfig, originConfigWithoutLanding } = generateCVConfig({
  name: 'taylor',
  rotatingNames: ['lisa', 'victor', 'jamie', 'dr', 'sami'],
  backgroundImage: '/assets/cv/taylor/background.jpeg',
  openGraphImage: '/assets/cv/taylor/opengraph-image.jpg',
  famousPeople: [
    {
      name: 'Taylor Swift',
      title: 'Global Music Icon',
      quote: "Personal branding is everything in today's digital world.",
      achievement: '500M+ followers',
      icon: Music,
      iconColor: 'bg-purple-700',
      quoteColor: 'text-purple-400',
      achievementColor: 'text-purple-300',
    },
    {
      name: 'Elizabeth Taylor',
      title: 'Hollywood Legend',
      quote: 'A memorable name opens doors to extraordinary opportunities.',
      achievement: '2x Oscar Winner',
      icon: Star,
      iconColor: 'bg-blue-700',
      quoteColor: 'text-blue-400',
      achievementColor: 'text-blue-300',
    },
    {
      name: 'Taylor Lautner',
      title: 'Actor & Producer',
      quote: 'Your domain is your digital identity.',
      achievement: 'Teen Choice Awards',
      icon: User,
      iconColor: 'bg-violet-700',
      quoteColor: 'text-violet-400',
      achievementColor: 'text-violet-300',
    },
    {
      name: 'James Taylor',
      title: 'Grammy Winner',
      quote: 'The right name becomes timeless.',
      achievement: 'Rock & Roll Hall of Fame',
      icon: Trophy,
      iconColor: 'bg-indigo-700',
      quoteColor: 'text-indigo-400',
      achievementColor: 'text-indigo-300',
    },
    {
      name: 'Zachary Taylor',
      title: '12th US President',
      quote: 'Leadership starts with how you present yourself.',
      achievement: 'Historical Legacy',
      icon: Briefcase,
      iconColor: 'bg-pink-700',
      quoteColor: 'text-pink-400',
      achievementColor: 'text-pink-300',
    },
  ],
  exampleProfiles: [
    {
      subdomain: 'jamie.taylor.cv',
      title: 'Product Designer',
      description: 'Portfolio & case studies',
      icon: User,
      gradient: 'from-cyan-400 to-blue-500',
      bgGradient: 'from-cyan-500/10 to-blue-500/10',
    },
    {
      subdomain: 'dr.taylor.cv',
      title: 'Medical Professional',
      description: 'Bio & scheduling links',
      icon: Briefcase,
      gradient: 'from-emerald-400 to-teal-500',
      bgGradient: 'from-emerald-500/10 to-teal-500/10',
    },
    {
      subdomain: 'band.taylor.cv',
      title: 'Music Collective',
      description: 'Link hub & streaming',
      icon: Music,
      gradient: 'from-purple-400 to-pink-500',
      bgGradient: 'from-purple-500/10 to-pink-500/10',
    },
    {
      subdomain: 'family.taylor.cv',
      title: 'Family Memorial',
      description: 'Multi-person mini site',
      icon: Heart,
      gradient: 'from-rose-400 to-orange-500',
      bgGradient: 'from-rose-500/10 to-orange-500/10',
    },
  ],
  testimonials: [
    {
      name: 'Alex M.',
      username: '@alexm',
      body: 'My band is called Taylor Made — this was perfect!',
      img: 'https://avatar.vercel.sh/alexm',
    },
    {
      name: 'Sarah K.',
      username: '@sarahk',
      body: "Got one for my daughter Taylor's graduation gift.",
      img: 'https://avatar.vercel.sh/sarahk',
    },
    {
      name: 'Taylor R.',
      username: '@taylorr',
      body: 'Clean URL for my freelance design work!',
      img: 'https://avatar.vercel.sh/taylorr',
    },
    {
      name: 'Jamie T.',
      username: '@jamiet',
      body: "Finally, a professional domain that's actually memorable.",
      img: 'https://avatar.vercel.sh/jamiet',
    },
    {
      name: 'Dr. Taylor',
      username: '@drtaylor',
      body: 'Perfect for my medical practice website.',
      img: 'https://avatar.vercel.sh/drtaylor',
    },
    {
      name: 'Band Taylor',
      username: '@bandtaylor',
      body: 'Our music collective needed this!',
      img: 'https://avatar.vercel.sh/bandtaylor',
    },
    {
      name: 'Family Taylor',
      username: '@familytaylor',
      body: 'Great for our family memorial site.',
      img: 'https://avatar.vercel.sh/familytaylor',
    },
    {
      name: 'Mike T.',
      username: '@miket',
      body: 'Best investment for my personal brand.',
      img: 'https://avatar.vercel.sh/miket',
    },
  ],
});

export { landingConfig, originConfigWithoutLanding };
