name: 'Determine Before Commit'
description: 'Determines the before commit hash or HEAD^'
author: 'D3ServeLabs'

inputs:
  working-directory:
    description: 'Working directory to run turbo from'
    required: false
    default: '.'

outputs:
  before-commit:
    description: 'Before commit hash or HEAD^'
    value: ${{ steps.determine-before-commit.outputs.before-commit }}

runs:
  using: 'composite'
  steps:
    - name: Determine before commit
      id: determine-before-commit
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "before: ${{ github.event.before }}"

        if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" || "${{ github.event.before }}" == "" ]]; then
          echo "before-commit='HEAD^'" >> $GITHUB_OUTPUT
        else
          echo "before-commit='${{ github.event.before }}'" >> $GITHUB_OUTPUT
        fi
branding:
  icon: 'git-branch'
  color: 'blue'
