version: '3.8'

services:
  app:
    image: ${APP_IMAGE}
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DD_ENV=prod
      - DD_SERVICE=ponder-indexer
      - DD_VERSION=1.2.3
      - PORT=8080
      - DATABASE_SCHEMA=indexer
      - PONDER_LOG_LEVEL=info
      - DATABASE_OVERRIDE_URL=${DATABASE_URL}
      - USE_WEBSOCKETS=${USE_WEBSOCKETS}
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    labels:
      com.datadoghq.ad.check_names: '["prometheus"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: >
        [{"prometheus_url":"http://%%host%%:8080/metrics", "namespace":"ponder-indexer", "metrics": ["ponder_*"]}]
      tags: "env:prod,team:infra,service:ponder-indexer"
      com.datadoghq.ad.logs: '[{"source": "ponder-indexer", "service": "ponder-indexer"}]'

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - ACME_EMAIL=${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    restart: always
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_CONTAINER_EXCLUDE=name:datadog-agent,name:caddy
      - DD_LOGS_ENABLED=true # Ensure log collection is enabled
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=false # Only collect logs from containers opted in via com.datadoghq.ad.logs labels
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  caddy_data:
  caddy_config:
