name: Deploy Backend to Cloud Run

on:
  # push:
  #   branches:
  #     - main    # Regular push to main branch deploys to production
  #     - prod
    # tags:
    #   - 'prod/v*'     # Tags like prod/v1.0.0 for production deployment
    #   - 'v*'          # Tags like v1.0.0 for production deployment
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }} # GCP project ID
  REGION: ${{ vars.GCP_REGION }} # GCP region
  REPO_NAME: ${{ vars.REPOSITORY_NAME }} # Artifact Registry repository name
  # Set different service names based on the trigger or tag pattern
  # Regular push to main branch or non-staging tags will deploy to production
  LABEL: >-
    ${{ 
      ((github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production') || 
         (github.event_name == 'push' && (github.ref == 'refs/heads/prod' || startsWith(github.ref, 'refs/tags/prod/') || startsWith(github.ref, 'refs/tags/v')))) 
        && 'prod' 
        || 'dev' 
    }}
  ENVIRONEMNT: test
  INFISICAL_SERVICE_TOKEN: ${{ 
      ((github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production') || 
         (github.event_name == 'push' && (github.ref == 'refs/heads/prod' || startsWith(github.ref, 'refs/tags/prod/') || startsWith(github.ref, 'refs/tags/v')))) 
        && secrets.INFISICAL_PROD_SERVICE_TOKEN 
        || secrets.INFISICAL_DEV_SERVICE_TOKEN 
    }}

jobs:
  build:
    name: Build and Deploy
    runs-on: 'blacksmith-4vcpu-ubuntu-2204'
    permissions:
      contents: read
      id-token: write # Required for GCP Workload Identity Federation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug step to see what environment we're deploying to
      - name: Debug environment variables
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Env name: ${{ env.LABEL }}"
          echo "Port: ${{ env.PORT }}"

      # Set up Google Cloud authentication using WIF
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_WIF_SERVICE_ACCOUNT }}

      # BEGIN - Docker auth and build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.REPO_NAME }}/namefi-astra-api-${{ env.LABEL }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" . -f apps/backend/Dockerfile
          docker push "${DOCKER_TAG}"

  # Deploy to Cloud Run (Backend API)
  deploy_api:
    name: Deploy to Cloud Run (Backend API)
    needs: [build]
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      id-token: write # Required for GCP Workload Identity Federation
    steps:
      # Set up Google Cloud authentication using WIF
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_WIF_SERVICE_ACCOUNT }}

      # BEGIN - Docker auth and build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (Backend/API)
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'namefi-astra-api-${{ env.LABEL }}'
          region: ${{ env.REGION }}
          project_id: '${{ env.PROJECT_ID }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.REPO_NAME }}/namefi-astra-api-${{ env.LABEL }}:${{ github.sha }}'

  # Deploy to Cloud Run (Temporal)
  deploy_temporal:
    name: Deploy to Cloud Run (Temporal)
    needs: [build]
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      id-token: write # Required for GCP Workload Identity Federation
    steps:
      # Set up Google Cloud authentication using WIF
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_WIF_SERVICE_ACCOUNT }}

      # BEGIN - Docker auth and build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      - name: Deploy to Cloud Run (Backend/Temporal)
        id: deploy-temporal
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'namefi-astra-temporal-${{ env.LABEL }}'
          region: ${{ env.REGION }}
          project_id: '${{ env.PROJECT_ID }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.REPO_NAME }}/namefi-astra-api-${{ env.LABEL }}:${{ github.sha }}'

      # Output the deployed URL
      - name: Show Output
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}"

  # Run the db migrations      
  migrate:
    name: Run the db migrations
    needs: [deploy_api, deploy_temporal]
    runs-on: 'blacksmith-4vcpu-ubuntu-2204'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Install dependencies
        run: bun install

      # - name: Add Infisical
      #   run: |
      #     curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
      #     sudo apt-get update && sudo apt-get install -y infisical
      
      - name: Run DB Migration
        working-directory: ./packages/db
        # run: bun with-env db:migrate
        run: bun db:migrate
