name: Validate

on:
  push:
    branches: [main]
  pull_request:

env:
  ENVIRONEMNT: test 

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.4"

      - name: Install dependencies
        run: bun install

      - name: Add Infisical
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      - name: Run validation
        run: bun validate

      - name: Run validation of secrets
        run: bun validate:secrets
        env:
          INFISICAL_SERVICE_TOKEN: ${{ secrets.INFISICAL_SERVICE_TOKEN }}
